config/routes.rb
Cards::Application.routes.draw do
  match 'tables/update' => 'tables#update'
  match 'tables/draw' => 'tables#draw'
  match 'tables/destroy' => 'tables#destroy'
  resources :tables do
    post 'create'
  end

  resources :hands

  resources :decks

  resources :cards

   root :to => 'tables#index'

end

app/models/hand.rb
class Hand
  @cards_in_hand = Array.new
  @@deck = nil
  @discards = nil

  def initialize(base_hand_amount,deck)
    @@deck = deck
    @cards_in_hand = @@deck.deal(base_hand_amount)
    @discards = Array.new
  end

  def show_hand 
    @cards_in_hand.map { |card| card.description } 
  end

  def play(index)
    @discards.push @cards_in_hand.delete_at(index)
  end
  
  def list_discards
    @discards.map { |card| card.description }
  end

  def draw
    @cards_in_hand = (@cards_in_hand << @@deck.deal(1)).flatten
  end
  
end

app/controllers/hands_controller.rb
class HandsController < ApplicationController
  # GET /hands
  # GET /hands.json
  def index
    @hands = Hand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hands }
    end
  end

  # GET /hands/1
  # GET /hands/1.json
  def show
    @hand = Hand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hand }
    end
  end

  # GET /hands/new
  # GET /hands/new.json
  def new
    @hand = Hand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hand }
    end
  end

  # GET /hands/1/edit
  def edit
    @hand = Hand.find(params[:id])
  end

  # POST /hands
  # POST /hands.json
  def create
    @hand = Hand.new(params[:hand])

    respond_to do |format|
      if @hand.save
        format.html { redirect_to @hand, notice: 'Hand was successfully created.' }
        format.json { render json: @hand, status: :created, location: @hand }
      else
        format.html { render action: "new" }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hands/1
  # PUT /hands/1.json
  def update
    @hand = Hand.find(params[:id])

    respond_to do |format|
      if @hand.update_attributes(params[:hand])
        format.html { redirect_to @hand, notice: 'Hand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hands/1
  # DELETE /hands/1.json
  def destroy
    @hand = Hand.find(params[:id])
    @hand.destroy

    respond_to do |format|
      format.html { redirect_to hands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hands_helper.rb
module HandsHelper
end

app/views/hands/_form.html.erb
<%= form_for(@hand) do |f| %>
  <% if @hand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hand.errors.count, "error") %> prohibited this hand from being saved:</h2>

      <ul>
      <% @hand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hands/edit.html.erb
<h1>Editing hand</h1>

<%= render 'form' %>

<%= link_to 'Show', @hand %> |
<%= link_to 'Back', hands_path %>

app/views/hands/index.html.erb
<h1>Listing hands</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hands.each do |hand| %>
  <tr>
    <td><%= link_to 'Show', hand %></td>
    <td><%= link_to 'Edit', edit_hand_path(hand) %></td>
    <td><%= link_to 'Destroy', hand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hand', new_hand_path %>

app/views/hands/new.html.erb
<h1>New hand</h1>

<%= render 'form' %>

<%= link_to 'Back', hands_path %>

app/views/hands/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_hand_path(@hand) %> |
<%= link_to 'Back', hands_path %>