config/routes.rb
Cards::Application.routes.draw do
  match 'tables/update' => 'tables#update'
  match 'tables/draw' => 'tables#draw'
  match 'tables/destroy' => 'tables#destroy'
  resources :tables do
    post 'create'
  end

  resources :hands

  resources :decks

  resources :cards

   root :to => 'tables#index'

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    if(!session[:table].nil?)
      @table = session[:table]
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end
  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params['players'].to_i,params['hand_size'].to_i)
    session[:table] = @table
    respond_to do |format|
        format.html { redirect_to tables_path, notice: 'Table was successfully created.' }
      end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    table = session[:table]
    player_id = params[:player_id]
    card_id = params[:card_id]
    table.player_play(player_id.to_i,card_id.to_i)
    session[:table] = table
    
    respond_to do |format|
        format.html { redirect_to tables_path, notice: 'Table was successfully updated.' }
    end
  end

  def draw
    respond_to do |format| 
    format.js {} 
    format.html { redirect_to tables_path, notice: 'Card Drawn.'}
    end
  end

  def destroy
    reset_session
    respond_to do |format|
      format.html { redirect_to tables_path, notice: 'Session Ended'}
    end
  end

end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/draw.html.erb
<%= yield %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<% if(session[:table].nil?) %>
  <h1>Welcome to your new game</h1>
  <%= form_tag(tables_path, :method => 'post') do  %>
    <p>
    <%= label_tag 'players','Number of Players:' %><br />
    <%= number_field_tag 'players',1 %><br />
    </p>
    <p>
    <%= submit_tag 'Start Game'%> | | <%= link_to 'View/Edit Cards', cards_path %>

    </p>
  <% end %>
<% else %>
  <div>
    <div>
      <span class="diceroll" id="roller">
        <input name="numberofdice" id="numberofdice" type="text">d<input name="sidesofdice" id="sidesofdice" type="text">
        <button class="diceroll" id="rollerbutton"> Roll!</button>
      </span>
      <span class="diceroll" id="diceresult"> </span>
    </div>

    <% @table.players.times do |player_number| %>
      <div class="hand" id = "hand<%= player_number + 1 %>">
        <p> <span> <%= button_tag( "Draw Card Player #{player_number + 1}", :class => 'draw', :id => "hand#{player_number + 1}", :remote => true) %>  </span></p>
      </div>
      <div class="discards" id="hand<%= player_number + 1 %>">
        <p> Discards </p>
      </div>

    <% end %>
    <div class="deck">
    <% @table.show_deck.each do |card_text| %>
      <p>
      <span> <%= card_text %> </span>
      </p>
    <%end%>
    </div>
  </div>
  <br />
  <%= link_to 'New Game', tables_destroy_path%>

<% end %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>